"use client";

import { useState } from "react";
import { useTranslations } from "next-intl";
import { ArrowDownIcon, ArrowUpIcon, PencilIcon, PlusIcon, SlidersHorizontalIcon, Trash2Icon } from "lucide-react";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Field, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { createOptionAction, createQuestionAction, createSectionAction, deleteOptionAction, deleteQuestionAction, deleteSectionAction, moveOptionAction, moveQuestionAction, moveSectionAction, saveRatingBoundsAction, updateOptionAction, updateQuestionAction, updateSectionAction } from "@/app/(platform)/surveys/draft-actions";
import type { SurveyQuestionDetail, SurveySectionDetail } from "@/lib/api/types";

const questionTypes = ["short_text", "long_text", "single_choice", "multiple_choice", "yes_no", "rating", "number", "date"] as const;
type Props = { surveyId: string; draftId: string; sections: SurveySectionDetail[] };

export function DraftSectionEditor({ surveyId, draftId, sections }: Props) {
  const t = useTranslations("surveys.editor");
  const sectionIds = sections.map((section) => section.id).join(",");
  return <div className="flex flex-col gap-5">
    <Card className="border-primary/20 bg-primary/[0.025]"><CardHeader><CardTitle className="font-heading">{t("addSection")}</CardTitle><CardDescription>{t("addSectionHint")}</CardDescription></CardHeader><CardContent><form action={createSectionAction.bind(null, surveyId, draftId)}><FieldGroup><Field><FieldLabel htmlFor="new-section-title">{t("title")}</FieldLabel><Input id="new-section-title" name="title" placeholder={t("sectionPlaceholder")} required /></Field><Field><FieldLabel htmlFor="new-section-description">{t("intro")} <span className="text-muted-foreground">{t("optional")}</span></FieldLabel><Textarea id="new-section-description" name="description" placeholder={t("sectionIntroPlaceholder")} rows={2} /></Field><Button type="submit" className="w-fit"><PlusIcon data-icon="inline-start" />{t("addSection")}</Button></FieldGroup></form></CardContent></Card>
    {sections.length ? <ol className="flex flex-col gap-3">{sections.map((section, index) => <li key={section.id}><Card><CardHeader className="gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="space-y-1.5"><p className="text-xs font-medium tracking-[0.16em] text-muted-foreground uppercase">{t("section", { number: index + 1 })}</p><CardTitle className="font-heading text-xl">{section.title}</CardTitle>{section.description ? <CardDescription>{section.description}</CardDescription> : null}</div><MoveButtons action={moveSectionAction.bind(null, surveyId, draftId)} ids={sectionIds} itemId={section.id} index={index} lastIndex={sections.length - 1} item="section" /></CardHeader><CardContent className="flex flex-col gap-5"><QuestionList surveyId={surveyId} draftId={draftId} sectionId={section.id} questions={section.questions} /><details className="rounded-lg border bg-muted/20 p-4"><summary className="flex cursor-pointer list-none items-center gap-2 text-sm font-medium"><PlusIcon className="size-4" />{t("addQuestion")}</summary><QuestionForm action={createQuestionAction.bind(null, surveyId, draftId, section.id)} /></details><div className="flex flex-wrap gap-2 border-t pt-4"><details><summary className="flex w-fit cursor-pointer list-none items-center gap-2 rounded-md px-3 py-2 text-sm font-medium hover:bg-muted"><PencilIcon className="size-4" />{t("editSection")}</summary><form action={updateSectionAction.bind(null, surveyId, draftId, section.id)} className="mt-3 w-full min-w-72 rounded-lg border bg-muted/25 p-4"><FieldGroup><Field><FieldLabel htmlFor={`section-title-${section.id}`}>{t("title")}</FieldLabel><Input id={`section-title-${section.id}`} name="title" defaultValue={section.title} required /></Field><Field><FieldLabel htmlFor={`section-description-${section.id}`}>{t("intro")}</FieldLabel><Textarea id={`section-description-${section.id}`} name="description" defaultValue={section.description ?? ""} rows={2} /></Field><Button type="submit" className="w-fit">{t("saveChanges")}</Button></FieldGroup></form></details><DeleteSection surveyId={surveyId} draftId={draftId} sectionId={section.id} /></div></CardContent></Card></li>)}</ol> : <div className="rounded-xl border border-dashed px-6 py-12 text-center"><p className="font-heading text-lg font-medium">{t("noSections")}</p><p className="mt-1 text-sm text-muted-foreground">{t("noSectionsHint")}</p></div>}
  </div>;
}

function MoveButtons({ action, ids, itemId, index, lastIndex, item, idsName = "sectionIds", itemName = "sectionId" }: { action: (formData: FormData) => void | Promise<void>; ids: string; itemId: string; index: number; lastIndex: number; item: "section" | "question" | "option"; idsName?: string; itemName?: string }) { const t = useTranslations("surveys.editor"); const itemLabel = t(`item.${item}`); return <div className="flex items-center gap-1"><form action={action}><input type="hidden" name={idsName} value={ids} /><input type="hidden" name={itemName} value={itemId} /><input type="hidden" name="direction" value="up" /><Button type="submit" variant="ghost" size="icon-sm" disabled={index === 0} aria-label={t("moveUp", { item: itemLabel })}><ArrowUpIcon /></Button></form><form action={action}><input type="hidden" name={idsName} value={ids} /><input type="hidden" name={itemName} value={itemId} /><input type="hidden" name="direction" value="down" /><Button type="submit" variant="ghost" size="icon-sm" disabled={index === lastIndex} aria-label={t("moveDown", { item: itemLabel })}><ArrowDownIcon /></Button></form></div>; }

function QuestionList({ surveyId, draftId, sectionId, questions }: { surveyId: string; draftId: string; sectionId: string; questions: SurveyQuestionDetail[] }) {
  const t = useTranslations("surveys.editor");
  if (!questions.length) return <p className="rounded-lg border border-dashed px-4 py-5 text-sm text-muted-foreground">{t("noQuestions")}</p>;
  const questionIds = questions.map((question) => question.id).join(",");
  return <ol className="flex flex-col gap-2">{questions.map((question, index) => <li key={question.id} className="rounded-lg border p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-medium text-muted-foreground">{t("question", { number: index + 1 })} · {questionTypes.includes(question.question_type as (typeof questionTypes)[number]) ? t(`types.${question.question_type as (typeof questionTypes)[number]}`) : question.question_type}</p><p className="mt-1 font-medium">{question.title}{question.is_required ? <span className="ml-1 text-destructive">*</span> : null}</p>{question.help_text ? <p className="mt-1 text-sm text-muted-foreground">{question.help_text}</p> : null}</div><div className="flex items-center gap-1"><MoveButtons action={moveQuestionAction.bind(null, surveyId, draftId, sectionId)} ids={questionIds} itemId={question.id} index={index} lastIndex={questions.length - 1} item="question" idsName="questionIds" itemName="questionId" /><DeleteQuestion surveyId={surveyId} draftId={draftId} sectionId={sectionId} questionId={question.id} /></div></div><details className="mt-3"><summary className="flex w-fit cursor-pointer list-none items-center gap-2 text-sm font-medium text-muted-foreground hover:text-foreground"><PencilIcon className="size-4" />{t("editQuestion")}</summary><QuestionForm action={updateQuestionAction.bind(null, surveyId, draftId, sectionId, question.id)} question={question} /></details><ChoiceOptions surveyId={surveyId} draftId={draftId} sectionId={sectionId} question={question} /><ValidationRules surveyId={surveyId} draftId={draftId} sectionId={sectionId} question={question} /></li>)}</ol>;
}

function ChoiceOptions({ surveyId, draftId, sectionId, question }: { surveyId: string; draftId: string; sectionId: string; question: SurveyQuestionDetail }) {
  const t = useTranslations("surveys.editor");
  if (question.question_type !== "single_choice" && question.question_type !== "multiple_choice") return null;
  const optionIds = question.options.map((option) => option.id).join(",");
  return <div className="mt-3 rounded-md border border-primary/15 bg-primary/[0.035] p-3"><p className="text-sm font-medium">{t("answerOptions")}</p><p className="mt-1 text-xs text-muted-foreground">{t("optionsHint")}</p><div className="mt-3 flex flex-col gap-2">{question.options.map((option, index) => <div key={option.id} className="rounded-md border bg-background p-2"><div className="flex items-center gap-1"><MoveButtons action={moveOptionAction.bind(null, surveyId, draftId, sectionId, question.id)} ids={optionIds} itemId={option.id} index={index} lastIndex={question.options.length - 1} item="option" idsName="optionIds" itemName="optionId" /><form action={deleteOptionAction.bind(null, surveyId, draftId, sectionId, question.id, option.id)} className="ml-auto"><Button type="submit" variant="ghost" size="icon-sm" aria-label={t("deleteOption")}><Trash2Icon /></Button></form></div><form action={updateOptionAction.bind(null, surveyId, draftId, sectionId, question.id, option.id)} className="mt-2 grid gap-2 sm:grid-cols-2"><Input name="optionLabel" aria-label={t("displayText")} defaultValue={option.label} required /><Input name="optionValue" aria-label={t("storedValue")} defaultValue={option.value} required /><Button type="submit" variant="outline" size="sm" className="w-fit">{t("saveOption")}</Button></form></div>)}</div><form action={createOptionAction.bind(null, surveyId, draftId, sectionId, question.id)} className="mt-3 flex flex-col gap-2 sm:flex-row"><Input name="optionLabel" placeholder={t("newOption")} required /><Button type="submit" size="sm" className="w-fit">{t("addOption")}</Button></form></div>;
}

function ValidationRules({ surveyId, draftId, sectionId, question }: { surveyId: string; draftId: string; sectionId: string; question: SurveyQuestionDetail }) {
  const t = useTranslations("surveys.editor");
  if (question.question_type !== "rating") return null;
  const minValidation = question.validations.find((validation) => validation.rule_type === "min_value");
  const maxValidation = question.validations.find((validation) => validation.rule_type === "max_value");
  return <details className="mt-3 rounded-md border border-dashed p-3" open={Boolean(minValidation || maxValidation)}>
    <summary className="flex cursor-pointer items-center gap-2 text-sm font-medium"><SlidersHorizontalIcon className="size-4" />{t("ratingScale")}</summary>
    <form action={saveRatingBoundsAction.bind(null, surveyId, draftId, sectionId, question.id, minValidation?.id ?? null, maxValidation?.id ?? null)} className="mt-3 grid gap-3 sm:grid-cols-[1fr_1fr_auto] sm:items-end">
      <Field>
        <FieldLabel htmlFor={`min-value-${question.id}`}>{t("minValue")}</FieldLabel>
        <Input id={`min-value-${question.id}`} name="minValue" type="number" step={1} defaultValue={minValidation ? String(minValidation.rule_value.value) : undefined} required />
      </Field>
      <Field>
        <FieldLabel htmlFor={`max-value-${question.id}`}>{t("maxValue")}</FieldLabel>
        <Input id={`max-value-${question.id}`} name="maxValue" type="number" step={1} defaultValue={maxValidation ? String(maxValidation.rule_value.value) : undefined} required />
      </Field>
      <Button type="submit" size="sm" className="w-fit">{t("save")}</Button>
    </form>
  </details>;
}

function DeleteQuestion({ surveyId, draftId, sectionId, questionId }: { surveyId: string; draftId: string; sectionId: string; questionId: string }) { const t = useTranslations("surveys.editor"); return <AlertDialog><AlertDialogTrigger render={<Button variant="ghost" size="icon-sm" className="text-destructive hover:text-destructive" aria-label={t("deleteQuestionLabel")} />}><Trash2Icon /></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{t("deleteQuestionTitle")}</AlertDialogTitle><AlertDialogDescription>{t("deleteQuestionDescription")}</AlertDialogDescription></AlertDialogHeader><form action={deleteQuestionAction.bind(null, surveyId, draftId, sectionId, questionId)}><AlertDialogFooter><AlertDialogCancel>{t("cancel")}</AlertDialogCancel><AlertDialogAction type="submit" variant="destructive">{t("delete")}</AlertDialogAction></AlertDialogFooter></form></AlertDialogContent></AlertDialog>; }
function DeleteSection({ surveyId, draftId, sectionId }: { surveyId: string; draftId: string; sectionId: string }) { const t = useTranslations("surveys.editor"); return <AlertDialog><AlertDialogTrigger render={<Button variant="ghost" className="text-destructive hover:text-destructive" />}><Trash2Icon data-icon="inline-start" />{t("deleteSection")}</AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{t("deleteSectionTitle")}</AlertDialogTitle><AlertDialogDescription>{t("deleteSectionDescription")}</AlertDialogDescription></AlertDialogHeader><form action={deleteSectionAction.bind(null, surveyId, draftId, sectionId)}><AlertDialogFooter><AlertDialogCancel>{t("cancel")}</AlertDialogCancel><AlertDialogAction type="submit" variant="destructive">{t("delete")}</AlertDialogAction></AlertDialogFooter></form></AlertDialogContent></AlertDialog>; }

function QuestionForm({ action, question }: { action: (formData: FormData) => void | Promise<void>; question?: SurveyQuestionDetail }) {
  const t = useTranslations("surveys.editor");
  const [type, setType] = useState(question?.question_type ?? "short_text");
  const [initialOptions, setInitialOptions] = useState(["", ""]);
  const supportsOther = type === "single_choice" || type === "multiple_choice";
  return <form action={action} className="mt-4"><FieldGroup><Field>{!question ? <><FieldLabel htmlFor="question-type">{t("questionType")}</FieldLabel><select id="question-type" name="questionType" value={type} onChange={(event) => setType(event.target.value as typeof type)} className="h-9 w-full rounded-md border bg-background px-3 text-sm">{questionTypes.map((value) => <option key={value} value={value}>{t(`types.${value}`)}</option>)}</select></> : null}</Field><Field><FieldLabel htmlFor={question ? `question-title-${question.id}` : "question-title"}>{t("question_")}</FieldLabel><Input id={question ? `question-title-${question.id}` : "question-title"} name="title" defaultValue={question?.title} placeholder={t("questionPlaceholder")} required /></Field><Field><FieldLabel htmlFor={question ? `question-help-${question.id}` : "question-help"}>{t("hint")} <span className="text-muted-foreground">{t("optional")}</span></FieldLabel><Textarea id={question ? `question-help-${question.id}` : "question-help"} name="helpText" defaultValue={question?.help_text ?? ""} rows={2} /></Field>{!question && supportsOther ? <Field><FieldLabel>{t("answerOptions")}</FieldLabel><p className="text-xs text-muted-foreground">{t("initialOptionsHint")}</p><div className="mt-2 flex flex-col gap-2">{initialOptions.map((option, index) => <div key={index} className="flex gap-2"><Input name="initialOption" value={option} onChange={(event) => setInitialOptions((current) => current.map((value, optionIndex) => optionIndex === index ? event.target.value : value))} placeholder={t("optionN", { number: index + 1 })} required={index < 2} />{initialOptions.length > 2 ? <Button type="button" variant="ghost" size="icon-sm" aria-label={t("removeOptionN", { number: index + 1 })} onClick={() => setInitialOptions((current) => current.filter((_, optionIndex) => optionIndex !== index))}><Trash2Icon /></Button> : null}</div>)}</div><Button type="button" variant="outline" size="sm" className="mt-2 w-fit" onClick={() => setInitialOptions((current) => [...current, ""])}><PlusIcon data-icon="inline-start" />{t("addOption")}</Button></Field> : null}<label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" name="isRequired" defaultChecked={question?.is_required} />{t("required")}</label>{supportsOther ? <label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" name="allowOther" defaultChecked={question?.allow_other} />{t("allowOther")}</label> : null}<Button type="submit" className="w-fit">{question ? t("saveQuestion") : t("addQuestion")}</Button></FieldGroup></form>;
}
