import Link from "next/link";
import { ArchiveIcon, ClipboardListIcon, PlusIcon } from "lucide-react";
import { getTranslations } from "next-intl/server";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Empty, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from "@/components/ui/empty";
import { listSurveys } from "@/lib/api/client";
import { getAccessToken } from "@/lib/auth/session";
export default async function SurveysPage({ searchParams }: PageProps<"/surveys">) { const t = await getTranslations("surveys"); const archived = (await searchParams).archived === "1"; const token = await getAccessToken(); const surveys = token ? await listSurveys(token, archived) : []; return <div className="mx-auto flex w-full max-w-7xl flex-col gap-8 px-4 py-7 sm:px-6 lg:px-10 lg:py-10"><section className="flex items-end justify-between gap-4"><div><p className="text-sm font-medium text-muted-foreground">{t("list.eyebrow")}</p><h1 className="mt-2 font-heading text-3xl font-semibold tracking-tight">{t("list.title")}</h1></div><div className="flex gap-2"><Button nativeButton={false} variant="outline" render={<Link href={archived ? "/surveys" : "/surveys?archived=1"} />}><ArchiveIcon data-icon="inline-start" />{archived ? t("list.hideArchive") : t("list.showArchive")}</Button><Button nativeButton={false} render={<Link href="/surveys/new" />}><PlusIcon data-icon="inline-start" />{t("list.new")}</Button></div></section>{surveys.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{surveys.map(s => <Link key={s.id} href={`/surveys/${s.id}`}><Card><CardHeader><Badge variant={s.status === "published" ? "default" : "secondary"}>{s.status === "archived" ? t("status.archived") : s.status === "published" ? t("status.published") : t("status.draft")}</Badge><CardTitle className="mt-4">{s.title}</CardTitle><CardDescription>{s.description || t("list.noDescription")}</CardDescription></CardHeader><CardContent>{t("list.openDetails")}</CardContent></Card></Link>)}</div> : <Empty className="min-h-72 border bg-card"><EmptyHeader><EmptyMedia variant="icon"><ClipboardListIcon /></EmptyMedia><EmptyTitle>{archived ? t("list.emptyArchived") : t("list.empty")}</EmptyTitle><EmptyDescription>{t("list.emptyHint")}</EmptyDescription></EmptyHeader></Empty>}</div>; }
