import Link from "next/link";
import { ArchiveIcon, ClipboardListIcon, PlusIcon } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Empty, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from "@/components/ui/empty";
import { listSurveys } from "@/lib/api/client";
import { getAccessToken } from "@/lib/auth/session";
export default async function SurveysPage({ searchParams }: PageProps<"/surveys">) { const archived = (await searchParams).archived === "1"; const token = await getAccessToken(); const surveys = token ? await listSurveys(token, archived) : []; return <div className="mx-auto flex w-full max-w-7xl flex-col gap-8 px-4 py-7 sm:px-6 lg:px-10 lg:py-10"><section className="flex items-end justify-between gap-4"><div><p className="text-sm font-medium text-muted-foreground">Umfragekatalog</p><h1 className="mt-2 font-heading text-3xl font-semibold tracking-tight">Umfragen</h1></div><div className="flex gap-2"><Button nativeButton={false} variant="outline" render={<Link href={archived ? "/surveys" : "/surveys?archived=1"} />}><ArchiveIcon data-icon="inline-start" />{archived ? "Archiv ausblenden" : "Archiv anzeigen"}</Button><Button nativeButton={false} render={<Link href="/surveys/new" />}><PlusIcon data-icon="inline-start" />Neue Umfrage</Button></div></section>{surveys.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{surveys.map(s => <Link key={s.id} href={`/surveys/${s.id}`}><Card><CardHeader><Badge variant={s.status === "published" ? "default" : "secondary"}>{s.status === "archived" ? "Archiviert" : s.status === "published" ? "Veröffentlicht" : "Entwurf"}</Badge><CardTitle className="mt-4">{s.title}</CardTitle><CardDescription>{s.description || "Ohne Beschreibung"}</CardDescription></CardHeader><CardContent>Details öffnen</CardContent></Card></Link>)}</div> : <Empty className="min-h-72 border bg-card"><EmptyHeader><EmptyMedia variant="icon"><ClipboardListIcon /></EmptyMedia><EmptyTitle>{archived ? "Keine archivierten Umfragen" : "Noch keine Umfragen"}</EmptyTitle><EmptyDescription>Erstellen Sie die erste Umfrage für den Katalog.</EmptyDescription></EmptyHeader></Empty>}</div>; }
