"""add clinic model

Revision ID: 965df37acb3c
Revises: 542f9cf23d06
Create Date: 2026-09-04 17:15:00.190837

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "965df37acb3c"
down_revision: str | Sequence[str] | None = "542f9cf23d06"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clinics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("logo_url", sa.String(length=2083), nullable=True),
        sa.Column("street", sa.String(length=255), nullable=True),
        sa.Column("hausnummer", sa.Integer(), nullable=True),
        sa.Column("city", sa.String(length=255), nullable=True),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_clinics_name"), "clinics", ["name"], unique=False)
    op.create_index(op.f("ix_clinics_slug"), "clinics", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_clinics_slug"), table_name="clinics")
    op.drop_index(op.f("ix_clinics_name"), table_name="clinics")
    op.drop_table("clinics")
    # ### end Alembic commands ###
